### ISSUE TITLE
Halt the program if the Encrypted Key is all zeros 

### ISSUE THREAD

**Issue by jeremy-daily** [SystemsCyber/CAN-Logger-3#13]
![image](https://user-images.githubusercontent.com/7162728/75114448-20a0d500-5613-11ea-8ea2-01af797b3553.png)

There's no way to use the data if this happens. We should rapidly flash all 4 LEDs on the logger if the ATECC chip doesn't calculate the session key.

**Comment by jeremy-daily** [comment]
Let's add a check during upload to reject the data file so we don't populate the database and S3 bucket with garbage files (i.e. files we don't know the key for)

**Comment by duyvan1995** [comment]
What are the conditions to reject the data?
